### ISSUE TITLE
Add dedicated section to `.github/dependabot.yml` for `docs/requirements.txt`

### ISSUE THREAD

**Issue by jwodder** [jwodder/pyrepo#40]
The `.github/dependabot.yml` template currently used by pyrepo causes Dependabot to open a PR if a `~=` version specifier in a `docs/requirements.txt` file does not use the latest version of the package as the lower limit.  This should be changed so that `~=` specifiers are only updated when the latest version no longer matches them.  Adding the following to `.github/dependabot.yml` for projects with documentation might fix it, but further research is needed:

```yaml
  - package-ecosystem: pip
    directory: /docs
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
    commit-message:
      prefix: "[python+docs]"
    labels:
      - dependencies
      - d:python
```

If this proves to be the correct approach, it should be added as a step to #3.
